/// Flutter icons Sumerico
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Sumerico
///      fonts:
///       - asset: fonts/Sumerico.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Sumerico {
  Sumerico._();

  static const _kFontFam = 'Sumerico';
  static const String? _kFontPkg = null;

  static const IconData arrow___down_3 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___up_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_square = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discovery = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
